### PR TITLE
documentation consistency across plugins

### PR DESCRIPTION
**Pull request by trebmuh**
Just a bit of it.
Hope that helps keeping people outside struggle.

(note that I don't know why but the sentence is talking about "Currently, convoLV2" even if I put "fil4.lv2" in my commit)

### CODE REVIEW

**Comment by x42** [comment]
heh, I didn't put that in :)
I started this plugin by simply copying convo.lv2's source structure.

Thanks for the corrections. It's very appreciated.

**Comment by x42** [comment]
Actually fil4.lv2 is known to work in all LV2 hosts. Ardour3,4, Mixbus, Qtractor, Carla, Ingen,.. (probably also lmms and audacity and more that I have not tested).

It also includes a standalone jack app `x42-eq`, I think giving an explicit `jalv.gtk` example is not needed.

**Comment by trebmuh** [comment]
> heh, I didn't put that in :)

Yes, I know. I did put something about fil4.lv2, but for a reason or another, when I asked for a pull request to your repo, it changed to convoLV2. That's maybe because I made a first patch (talking about convoLV2 by mistake) within a fork of your repo, then I deleted it, then I made a second patch which was (rightly this time) talking about fil4.lv2 but when I asked to pull it to your repo, it changed back to convoLV2. Certainly something around a buffer on the github web interface or in my web browser... or it might be because I'm still fairly new to git and github and the problem would then be between the chair and the keyboard :)

> It also includes a standalone jack app x42-eq, I think giving an explicit jalv.gtk example is not needed.

That make sense. Are you talking of "x42-fil4" when you write "x42-eq" ? Or did I miss something and there is another stand-alone app ?

**Comment by trebmuh** [comment]
I was looking at the stand-alone "x42-fil4". Is there any way to save preset with it ? That would be so far my only reason to keep using jalv.gtk to access fil4.lv2 .

**Comment by x42** [comment]
Right `x42-fil4` (the makefile just suffixes the plugin-name). It's renamed in the binary bundles.

**Comment by x42** [comment]
There is currently no preset or state support in the standalone jack-app. That may or may not happen (probably not, because saving presets requires a UI, loading presets may be made available via a commandline option, robtk/jackwrap.c is a LV2 host).

However, you can specify initial values on the comandline and also remote-control it via OSC.

**Comment by trebmuh** [comment]
ok, thanks for the answer

**Pull request closed without merging**
