### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by trebmuh** [comment]
ping :)

**Comment by x42** [comment]
Oh I forgot about that.  I didn't merge it because one uses a full-stop is only at the end of a sentence, not for enumerations or lists.

I'll fix the upper-case after colon  (bad german habit) and typos though.

**Comment by x42** [comment]
Could you have another look, that I didn't miss anything?  Thanks!

**Comment by trebmuh** [comment]
Sweet. I'm going away for 4 weeks on tomorrow so I might check that again in about one month.
Enjoy your July month !

**Comment by trebmuh** [comment]
I realize now that I didn't followed up with that, it just went out of my eyes.
All was good here, indeed.

**Pull request closed without merging**
